name: Deploy with Coolify

on:
  push:
    branches:
      - main  # Déclenchement uniquement sur la branche "test"

jobs:
  deploy:

    steps:
      - name: Trigger Coolify deploy
        run: |
          curl -X POST "https://coolify.dev.eclair.ec-lyon.fr/api/v1/deploy?uuid=skoskgg0og8sss0880oow48c&force=false" \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}" \
          -H "Content-Type: application/json"
